version: '3.3'

services:



  postgres:
    build:
      context: database
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=incluitech
    restart: unless-stopped

volumes:
  postgres-data: