version: '3.3'

services:

  solucao-de-problemas-service:
    build:
      context: ./solucao-de-problemas-service
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: "solucao-de-problemas-service"
    restart: unless-stopped
    environment:
      - 'spring.datasource.url=jdbc:postgresql://incluitech-postgres:5432/incluitech'
      - 'spring.datasource.username=postgres'
      - 'spring.datasource.password=postgres'
    ports:
      - "8080:8080"
    depends_on:
      - incluitech-postgres
    links:
      - incluitech-postgres


  chatbot-service:
    build:
      context: ./chatbot-service
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: "chatbot-service"
    restart: unless-stopped
    ports:
      - "8081:8080"


  incluitech-postgres:
    build:
      context: database
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: "incluitech-postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=incluitech
    restart: unless-stopped

volumes:
  postgres-data: