CREATE DATABASE IF NOT EXISTS incluitech;

CREATE USER IF NOT EXISTS postgres;
GRANT ALL PRIVILEGES ON DATABASE incluitech TO postgres;

CREATE TABLE IF NOT EXISTS usuario(
    id SERIAL PRIMARY KEY,
    nome VARCHAR (50) NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT NOW()
);